name: Update PR Triage Board

on:
  schedule:
    - cron: '13 * * * *'  # Every hour
  workflow_dispatch:  # Allows triggering manually from the UI

jobs:
  update-pr-triage-board:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Triage Bot
        uses: yuvipanda/pr-triage-board-bot@main
        with:
          organization: 'jupyterlab'
          project-number: '11'
          gh-app-id: '1842581'
          gh-app-installation-id: '82755492'
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
